/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.pojo;

/**
 * @author Javeriana
 */
public class AtrPersonalizadoPojo {

    private Long id;

    private String nombre;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}