/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.pojo;

/**
 * @author Javeriana
 */
public class CierreSolicitudPojo {

    private Long id;

    private String respuesta;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the respuesta
	 */
	public String getRespuesta() {
		return respuesta;
	}

	/**
	 * @param respuesta the respuesta to set
	 */
	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}
}