/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.pojo;

/**
 * @author Javeriana
 */
public class DatoAtrPersonalizadoPorUsuarioPojo {

    private String nombreAtrPersonalizado;

    private String respuestaAtrPersonalizado;

	/**
	 * @return the nombreAtrPersonalizado
	 */
	public String getNombreAtrPersonalizado() {
		return nombreAtrPersonalizado;
	}

	/**
	 * @param nombreAtrPersonalizado the nombreAtrPersonalizado to set
	 */
	public void setNombreAtrPersonalizado(String nombreAtrPersonalizado) {
		this.nombreAtrPersonalizado = nombreAtrPersonalizado;
	}

	/**
	 * @return the respuestaAtrPersonalizado
	 */
	public String getRespuestaAtrPersonalizado() {
		return respuestaAtrPersonalizado;
	}

	/**
	 * @param respuestaAtrPersonalizado the respuestaAtrPersonalizado to set
	 */
	public void setRespuestaAtrPersonalizado(String respuestaAtrPersonalizado) {
		this.respuestaAtrPersonalizado = respuestaAtrPersonalizado;
	}
}