/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.pojo;

/**
 * @author Javeriana
 */
public class InscripcionPojo {

    private Long id;

    private String dato;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the dato
	 */
	public String getDato() {
		return dato;
	}

	/**
	 * @param dato the dato to set
	 */
	public void setDato(String dato) {
		this.dato = dato;
	}

	
}