/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.entidades;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Javeriana
 */
@Embeddable
public class DiasSemanaEnum {

    @Basic
    private String LUNES;

    @Basic
    private String MARTES;

    @Basic
    private String MIERCOLES;

    @Basic
    private String JUEVES;

    @Basic
    private String VIERNES;

    @Basic
    private String SABADO;

    @Basic
    private String DOMINGO;

    public String getLUNES() {
        return this.LUNES;
    }

    public void setLUNES(String LUNES) {
        this.LUNES = LUNES;
    }

    public String getMARTES() {
        return this.MARTES;
    }

    public void setMARTES(String MARTES) {
        this.MARTES = MARTES;
    }

    public String getMIERCOLES() {
        return this.MIERCOLES;
    }

    public void setMIERCOLES(String MIERCOLES) {
        this.MIERCOLES = MIERCOLES;
    }

    public String getJUEVES() {
        return this.JUEVES;
    }

    public void setJUEVES(String JUEVES) {
        this.JUEVES = JUEVES;
    }

    public String getVIERNES() {
        return this.VIERNES;
    }

    public void setVIERNES(String VIERNES) {
        this.VIERNES = VIERNES;
    }

    public String getSABADO() {
        return this.SABADO;
    }

    public void setSABADO(String SABADO) {
        this.SABADO = SABADO;
    }

    public String getDOMINGO() {
        return this.DOMINGO;
    }

    public void setDOMINGO(String DOMINGO) {
        this.DOMINGO = DOMINGO;
    }

}