/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.entidades;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Javeriana
 */
@Entity
public class Dominio {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToMany(targetEntity = Lugar.class)
    private List<Lugar> lugares;

    @OneToMany(targetEntity = Servicios.class)
    private List<Servicios> servicios;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<Lugar> getLugares() {
        return this.lugares;
    }

    public void setLugares(List<Lugar> lugares) {
        this.lugares = lugares;
    }

    public List<Servicios> getServicios() {
        return this.servicios;
    }

    public void setServicios(List<Servicios> servicios) {
        this.servicios = servicios;
    }

}