/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.entidades;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author Javeriana
 */
@Entity
public class Etiqueta {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private String categoria;

    @ManyToMany(targetEntity = UsuarioJaveriana.class, mappedBy = "preferencias")
    private List<UsuarioJaveriana> usuarioJaverianas;

    @ManyToMany(targetEntity = Evento.class, mappedBy = "etiquetas")
    private List<Evento> eventos;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategoria() {
        return this.categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public List<UsuarioJaveriana> getUsuarioJaverianas() {
        return this.usuarioJaverianas;
    }

    public void setUsuarioJaverianas(List<UsuarioJaveriana> usuarioJaverianas) {
        this.usuarioJaverianas = usuarioJaverianas;
    }

    public List<Evento> getEventos() {
        return this.eventos;
    }

    public void setEventos(List<Evento> eventos) {
        this.eventos = eventos;
    }

}