/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.entidades;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Lob;

/**
 * @author WORLD OFFICE
 */
@Entity
public class Universidad extends Dominio {

    @Basic
    private String url;

    @Lob
    @Basic
    private byte[] imagen;
    
	@Basic
    private String nombreArchivo;
	

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public byte[] getImagen() {
        return this.imagen;
    }

    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }

	/**
	 * @return the nombreArchivo
	 */
	public String getNombreArchivo() {
		return nombreArchivo;
	}

	/**
	 * @param nombreArchivo the nombreArchivo to set
	 */
	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}
}