/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SIEEJ.entidades;

import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.OneToMany;

/**
 * @author Javeriana
 */
@Entity
public class Universidad extends Usuario {

	@Basic
    private String url;
    
    @Lob
    @Basic
    private byte[] imagen;
    
    @OneToMany(targetEntity = Lugar.class)
    private List<Lugar> lugares;

    public List<Lugar> getLugares() {
        return this.lugares;
    }

    public void setLugares(List<Lugar> lugares) {
        this.lugares = lugares;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public byte[] getImagen() {
        return this.imagen;
    }

    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
}