/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SIEEJ.entidades;

import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;

/**
 * @author Javeriana
 */
@Entity
public class Universidad {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
	
	@Basic
    private String url;
	
	@Basic
    private Boolean activo;
	
	@Basic
    private String nombreUniversidad;
	
    @Lob
    @Basic
    private byte[] imagen;
    
    @OneToMany(targetEntity = Lugar.class)
    private List<Lugar> lugares;

    public String getNombreUniversidad() {
		return nombreUniversidad;
	}

	public Long getId() {
		return id;
	}

	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setNombreUniversidad(String nombreUniversidad) {
		this.nombreUniversidad = nombreUniversidad;
	}

	public List<Lugar> getLugares() {
        return this.lugares;
    }

    public void setLugares(List<Lugar> lugares) {
        this.lugares = lugares;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public byte[] getImagen() {
        return this.imagen;
    }

    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
}