/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SIIEJ.entidades;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author Javeriana
 */
@Entity
public class Actividad extends Evento {

    @Basic
    private String nombre;

    @OneToMany(targetEntity = Horario.class)
    private List<Horario> horarios;

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List<Horario> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(List<Horario> horarios) {
        this.horarios = horarios;
    }

}