/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SIIEJ.entidades;

import javax.persistence.Entity;

/**
 * @author Javeriana
 */
@Entity
public class AdminJaveriana extends Usuario {

}