/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.enumeracion;

/**
 * Enumera los niveles (estados) de los usuarios del sistema
 * @author Javeriana
 */
public enum EstadoEnum {
	NUEVO,
	JUNIOR,
	INTERMEDIO,
	SENIOR,
	VIP,
	ULTRALEGENDARIO;
}
   