/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.model.general;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author Javeriana
 */
@Entity
public class DatoPersonalizado {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Basic
    private String dato;
    
    @ManyToOne
    private UsuarioJaveriana usuarioJaveriana;
    
    @ManyToOne
    private AtrPersonalizado atrPersonalizado;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the dato
	 */
	public String getDato() {
		return dato;
	}

	/**
	 * @param dato the dato to set
	 */
	public void setDato(String dato) {
		this.dato = dato;
	}

	/**
	 * @return the usuarioJaveriana
	 */
	public UsuarioJaveriana getUsuarioJaveriana() {
		return usuarioJaveriana;
	}

	/**
	 * @param usuarioJaveriana the usuarioJaveriana to set
	 */
	public void setUsuarioJaveriana(UsuarioJaveriana usuarioJaveriana) {
		this.usuarioJaveriana = usuarioJaveriana;
	}

	/**
	 * @return the atrPersonalizado
	 */
	public AtrPersonalizado getAtrPersonalizado() {
		return atrPersonalizado;
	}

	/**
	 * @param atrPersonalizado the atrPersonalizado to set
	 */
	public void setAtrPersonalizado(AtrPersonalizado atrPersonalizado) {
		this.atrPersonalizado = atrPersonalizado;
	}
}