/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.model.general;

import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonIgnore;

import co.com.javeriana.SICE2.enumeracion.TipoDominioEnum;

/**
 * @author Javeriana
 */
@Entity
public class Dominio {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Basic
    private String nombre;
    
	@Basic
	private Boolean activo;
	
	@Basic
	private Boolean nacional;

    @Basic
    private String url;
    
    @Basic
    private Long idUsuarioCreador;
    
    @Basic
    @Enumerated(value = EnumType.STRING)
    private TipoDominioEnum tipo;

    @Lob
    @Basic
    private byte[] imagen;
    
	@Basic
    private String nombreArchivo;
	
	@JsonIgnore
    @OneToMany(targetEntity = Lugar.class)
    private List<Lugar> lugares;

	@JsonIgnore
    @OneToMany(targetEntity = Servicio.class, mappedBy="dominio")
    private List<Servicio> servicios;

    
	/**
	 * @return the idUsuarioCreador
	 */
	public Long getIdUsuarioCreador() {
		return idUsuarioCreador;
	}

	/**
	 * @param idUsuarioCreador the idUsuarioCreador to set
	 */
	public void setIdUsuarioCreador(Long idUsuarioCreador) {
		this.idUsuarioCreador = idUsuarioCreador;
	}

	/**
	 * @return the nacional
	 */
	public Boolean getNacional() {
		return nacional;
	}

	/**
	 * @param nacional the nacional to set
	 */
	public void setNacional(Boolean nacional) {
		this.nacional = nacional;
	}

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @return the tipo
	 */
	public TipoDominioEnum getTipo() {
		return tipo;
	}

	/**
	 * @param tipo the tipo to set
	 */
	public void setTipo(TipoDominioEnum tipo) {
		this.tipo = tipo;
	}

	/**
	 * @param url the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the imagen
	 */
	public byte[] getImagen() {
		return imagen;
	}

	/**
	 * @param imagen the imagen to set
	 */
	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	/**
	 * @return the nombreArchivo
	 */
	public String getNombreArchivo() {
		return nombreArchivo;
	}

	/**
	 * @param nombreArchivo the nombreArchivo to set
	 */
	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}
	

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the activo
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * @param activo the activo to set
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	/**
	 * @return the lugares
	 */
	public List<Lugar> getLugares() {
		return lugares;
	}

	/**
	 * @param lugares the lugares to set
	 */
	public void setLugares(List<Lugar> lugares) {
		this.lugares = lugares;
	}

	/**
	 * @return the servicios
	 */
	public List<Servicio> getServicios() {
		return servicios;
	}

	/**
	 * @param servicios the servicios to set
	 */
	public void setServicios(List<Servicio> servicios) {
		this.servicios = servicios;
	}

}