/**
 * This file was generated by the Jeddict
 */
package co.com.javeriana.SICE2.model.general;

import javax.persistence.Entity;

/**
 * @author Javeriana
 */
@Entity
public class Egresado extends UsuarioJaveriana {

}